language: python

sudo: false

dist: trusty

python:
  - "3.6"

install:
  - pip install -r requirements.txt  
  
#before_install:
# - chmod +x mvnw
 
before_script:
  - pip install codecov && codecov -t 282fb639-6547-4822-abeb-32b13032e468
  
script: python manage.py test
  
after_success:
  - codecov
  
branches:
  only:
  - master
  
cache:
  directories:
  - .autoconf