# Generated by Django 2.1 on 2018-08-14 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180814_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
